<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="xixiaozhuas-MacBook-Pro.local" ignored="2" name="/Users/tomorrowisly/FactoryMode" tests="3" failures="1" timestamp="2022-05-09T12:37:23 CST" time="0.586" errors="0">
  <testcase name="test_2" time="0.103" classname="org.testNg.runTest"/>
  <testcase name="test_2" time="0.003" classname="org.testNg.runTest"/>
  <testcase name="test_1" time="0.037" classname="org.testNg.runTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testNg.runTest.test_1() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testNg.runTest.test_1() didn't finish within the time-out 1
]]>
    </failure>
  </testcase> <!-- test_1 -->
  <testcase name="test_3" time="0.0" classname="org.testNg.runTest">
    <ignored/>
  </testcase> <!-- test_3 -->
  <testcase name="test_4" time="0.0" classname="org.testNg.runTest">
    <ignored/>
  </testcase> <!-- test_4 -->
</testsuite> <!-- /Users/tomorrowisly/FactoryMode -->
