<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="xixiaozhuas-MacBook-Pro.local" name="org.testNg.runTest" tests="3" failures="0" timestamp="2022-05-09T12:37:23 CST" time="0.143" errors="1">
  <testcase name="test_2" time="0.003" classname="org.testNg.runTest"/>
  <testcase name="test_2" time="0.103" classname="org.testNg.runTest"/>
  <testcase name="test_1" time="0.037" classname="org.testNg.runTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testNg.runTest.test_1() didn&#039;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testNg.runTest.test_1() didn't finish within the time-out 1
]]>
    </error>
  </testcase> <!-- test_1 -->
</testsuite> <!-- org.testNg.runTest -->
